---
title: 'Class 05: Web Scraping'
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro to `robotstxt`

From the class activity, let us look at the <https://www.indeed.com/jobs/> example. 

```{r indeed, warning=FALSE}
robotstxt::paths_allowed(
  paths= "/jobs/",
  domain = "https://www.indeed.com"
)
```

Given that this returned `TRUE`, it means that we are allowed to scrape this webpage (directory from the website).


# The BLS Scrape Example


```{r bls_scrape}
# step 0 is confirming that I can scrape the directory/webpage
# Returned true so I can srape this
robotstxt::paths_allowed(
  paths = "/emp/",
  domain = "https://www.bls.gov/"
)

# step 1
resp = httr2::request(
  "https://www.bls.gov/emp/tables/fastest-growing-occupations.htm"
  ) |> 
  httr2::req_user_agent("An ISA 401 Bot from Miami University") |> 
  httr2::req_perform()

bls_webpage = resp |> httr2::resp_body_raw() |> rvest::read_html()
bls_webpage
```


